### ISSUE TITLE
software download issues

### ISSUE THREAD

**Issue by RameshwarTiwari** [compomics/meta-proteome-analyzer#10]
I am using windows 10 and after installing JAVA successfully. I have installed Metaproteomeanalyzer version 1.5.0. however, I am not able to access this software. I can only see the opening page of the software showing version 1.5.0 and release date 01/05/2017.

Please help me to use this software as it is very essential for my study.

Thanks
![picture1](https://cloud.githubusercontent.com/assets/28917137/26626452/e77a66bc-4614-11e7-8a7f-a653618afbdb.png)

**Comment by thilus** [comment]
Dear RameshwarTiwari,

for your reported issue: could you try to use the latest version 1.6.0 please.

Please leave a comment, if the issue still occurs. 

Best,
Thilo

**Comment by RameshwarTiwari** [comment]
Dear Thilo
Thanks for your response. Here in this site only MPA Portable version 1.7.0 is available.

If possible can you please provide me the 1.6.0 version.

Thanks

Regards
Rameshwar

**Comment by thilus** [comment]
Dear Rameshwar,

oh, the latest version 1.7.0 should be improved compared to the 1.6.0 (in particular in speed on the front-end side). Could you please try the latest version?

Thanks again, best,
Thilo
