### ISSUE TITLE
Uniprot Database Error

### ISSUE THREAD

**Issue by PaulAdrian89** [compomics/meta-proteome-analyzer#11]
When using the command line to run MPA, I get the following error message when fetching Uniprot entries: 
ERROR [main] u.a.e.u.d.s.a.DBCrossReferenceConverter [DBCrossReferenceConverter.java:40] DatabaseType: SFLD is unknown.

I've checked all database identifiers from my protein fasta and they all correspond to Swiss-Prot (sp).
Is it possible that changes in the Uniprot services are causing this issue? Is there a solution to change anything in the java code to avoid this?

**Comment by thilus** [comment]
Thank you for reporting this issue.

Could be an UniProt service issue indeed - they change their API quite frequently.
Did it happen for all protein entries or only a few?

**Comment by thilus** [comment]
Update: the latest version of MPA (version 1.8.0) now holds the updated UniProtJAPI (version 1.0.16): the UniProt services should now run as expected.
